# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13a8xup0Rvy1LTSIAGgaJ4J9fLTlaTZ2Z
"""

import streamlit as st
import numpy as np
import pickle

# Load trained model
model = pickle.load(open('model.pkl', 'rb'))

st.set_page_config(page_title="Student Grade Predictor", layout="centered")

st.title("🎓 Student Academic Performance Predictor")
st.markdown("This app predicts the final grade (G3) based on student academic and behavioral inputs.")

# Sidebar for student inputs
st.sidebar.header("📋 Enter Student Info")

G1 = st.sidebar.slider("First Period Grade (G1)", 0, 20, 10)
G2 = st.sidebar.slider("Second Period Grade (G2)", 0, 20, 10)
failures = st.sidebar.selectbox("Number of Past Class Failures", [0, 1, 2, 3])
absences = st.sidebar.slider("Total Absences", 0, 100, 5)
studytime = st.sidebar.selectbox("Weekly Study Time (hours)", [1, 2, 3, 4])

# Input array (must match model features)
input_data = np.array([[G1, G2, failures, absences, studytime]])

# Predict and display result
if st.sidebar.button("Predict Final Grade"):
    prediction = model.predict(input_data)[0]
    st.success(f"📘 Predicted Final Grade (G3): **{round(prediction, 2)}** / 20")